services:
  web:
    image: drewhy98/devops_shop_web:1.0
    ports:
      - "8081:80"
    environment:
      DB_SERVER: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: shopdb
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
